name: Auto Assign and Label PR

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0

        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto-assign-config.yml"
